# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 천현철
title: 소프트웨어 엔지니어
email: chc3484@gmail.com
website: velog.io/@james-chun-dev

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  coolishbee
# stackoverflow_username: "13593441"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: james_cheon7
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs  
  11년 차 개발자로 PC/모바일 게임 개발과 Android/iOS/Unity SDK 개발을 해왔습니다. 현재는 <mark>Android, iOS, Unity SDK</mark>를 개발 중이며, 언어는 Java, Kotlin, Objc, Swift, C# 를 사용하고 있습니다.
  
  평소 일상생활에서도 개발에 관련해서 고민하고 사용자의 불편함을 개선하는 것을 좋아합니다. 그리고 항상 새로운 기술, 새로운 트렌드를 즐기고 있으며 팀 협업과 커뮤니케이션을 중요하게 생각하는 사람입니다.

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Language                
        description: | # this will include new lines to allow paragraphs
            C, C++, C#, Objective-C, Golang, Swift, Kotlin

      - layout: left
        title: Framework/Library                
        description: | # this will include new lines to allow paragraphs
            <mark>C++ :</mark> STL, Win32, WinAPI, MFC, DirectX, [Cocos2d-x](https://github.com/cocos2d/cocos2d-x), RideEngine, ZerodinEngine

            <mark>Unity :</mark> WebRTC, NGUI, EZGUI, Prime31, GPGS, Firebase, Facebook, AmazonSDK(GameCircle, AmazonCloudMessage), Kochava, GCM, Kakao, bazaarSDK, G-Presto, Adbrix, BestHTTP, EasyAR, Vuforia, Sqlite

            <mark>Android :</mark> Retrofit2, Firebase, GoogleSignIn, Facebook, Gson, ButterKnife, Google Billing Library, Jcenter, Maven, Gradle, Glide, FCM, AppleLogin, Coroutine, DataBinding, Proguard, [acra](https://github.com/ACRA/acra)

            <mark>iOS :</mark> AFNetworking, JSONModel, Firebase, Facebook, AppleLogin, Storekit, APNS, Cocoapod, Combine, Alamofire, SwiftUI, XCTest, SPM, Carthage, CoreData, Realm, [plcrashreporter](https://github.com/microsoft/plcrashreporter)

            <mark>Golang :</mark> [gin](https://github.com/gin-gonic/gin), [fyne](https://github.com/fyne-io/fyne), goquery, gorm, redigo
      
      - layout: left
        title: Dev Tools
        description: | # this will include new lines to allow paragraphs
            Visual Studio, Visual Studio Code, Android Studio, X-Code, Unity Engine, Sublime Text, Hudson, Jenkins, fastlane

      - layout: left
        title: Communication Tools
        description: | # this will include new lines to allow paragraphs
            Redmine, JIRA, Confluence, Slack, Mantis, Trello, TaskWorld, JANDI

      - layout: left
        title: Version Control System
        description: | # this will include new lines to allow paragraphs
            SVN, Github, Bitbucket, Gitlab, Bonobo git, Azure DevOps

  - title: Open-source # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universal SDK Unity
        link: github.com/coolishbee/universal-sdk-unity
        # link_text: AssetStore
        additional_links:
          - title: coolishbee/universal-sdk-unity-demo
            icon: fab fa-github
            url: github.com/coolishbee/universal-sdk-unity-demo
        quote: >
          로그인, 결제, 푸쉬 등 외부 라이브러리들을 통합한 유니티엔진용 SDK
        description: | # this will include new lines to allow paragraphs
          - 소셜 로그인(Google, Facebook, Apple)
          - 인앱 결제(Google, Apple)
          - Push(FCM, APNS)
          - 안드로이드(CustomTabView), iOS(SafariViewController)
          - [유니티 에셋스토어 출시](https://assetstore.unity.com/packages/slug/204843)          
          - [Universal SDK Android](https://github.com/coolishbee/universal-sdk-android-kotlin)          
          - [Universal SDK iOS](https://github.com/coolishbee/universal-sdk-ios-swift)      
      
      - layout: left
        title: iOS 유튜브 영상 검색 앱
        link: github.com/coolishbee/youtube-channel-filter-ios
        additional_links:
          - title:  coolishbee/
            icon: fab fa-github
            url: github.com/coolishbee/youtube-channel-filter-ios
        quote: >
          Swift + 스토리보드 + xib
        description: | # this will include new lines to allow paragraphs
          - Youtube API 연동
          - RealmSwift 연동          
      
      - layout: left
        title: iOS IT회사 정보 검색 앱
        link: github.com/coolishbee/company-scanner-ios
        additional_links:
          - title:  coolishbee/
            icon: fab fa-github
            url: github.com/coolishbee/company-scanner-ios
        quote: >
          SwiftUI + MapKit + MVVM
        description: | # this will include new lines to allow paragraphs
          - MapKit API 연동
          - CoreData 연동
      
      - layout: left
        title: go 백엔드 프레임워크
        link: github.com/coolishbee/go-gin-sample
        additional_links:
          - title:  coolishbee/
            icon: fab fa-github
            url: github.com/coolishbee/go-gin-sample
        quote: >
          golang + gin + swagger + mariadb sample
        description: | # this will include new lines to allow paragraphs
          - RESTful API
          - 소셜 로그인 token 백엔드 검증(구글, 페북, 애플)
          - Logging
          - Swagger 제공


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 게임펍
        link: gamepub.co.kr
        # link_text: boringcompany.com
        sub_title: SDK Developer
        caption: 2020.03 ~ 현재
        quote: >
          <mark>Unity</mark> <mark>C#</mark> <mark>AndroidJava</mark> <mark>Objective-C</mark> <mark>Kotlin</mark> <mark>Swift</mark> <mark>Maven</mark> <mark>Gradle</mark> <mark>Cocoapod</mark> <mark>Fastlane</mark>
        description: | # this will include new lines to allow paragraphs
            - Android SDK 개발
            - iOS SDK 개발
            - Unity SDK 개발
            - 소셜 로그인(Google, Facebook, Apple)
            - 인앱 결제(Google, Apple, OneStore)
            - Push(FCM, APNS)
            - 네트워크 통신([Retrofit2 + Coroutine](https://github.com/coolishbee/retrofit2-coroutine-example), [Alamofire](https://github.com/coolishbee/AlamofireExample))
            - [Unity Package Export Tool](https://github.com/coolishbee/unity-export-package-tool)
            - [fastlane과 Jenkins를 이용한 SDK 배포 자동화](https://github.com/coolishbee/docs/blob/main/ci/jenkins-usage.md)
            - [Unity Editor 를 활용한 빌드머신(feat. shell)](https://github.com/coolishbee/docs/blob/main/unity/unity-build-machine-shell.md)
            - [Android SDK Jcenter 배포](https://github.com/coolishbee/docs/blob/main/android/jcenter.md)
            - [Android SDK Maven 배포(Sonatype 을 통한 배포)](https://github.com/coolishbee/docs/blob/main/android/maven-deploy.md)
            - [SDK 사용 가이드 제공](https://docs.igamepub.co.kr)

      - layout: left
        title: 프리랜서
        link: https://youtu.be/1voJ_RI_h1k
        sub_title: Software Engineer
        caption: 2019.11 ~ 2020.01
        quote: >        
          5G 기반 자율주행 무인 경비로봇 원격제어 솔루션 개발
        description: | # this will include new lines to allow paragraphs            
            <mark>custom opencv sdk 플러그인 개발</mark>
            - opencv dll 프로젝트에 연동
            - c++, c# 간에 통신하는 Interface 및 Data Convert 설계 및 개발            
            - 테스트용 c# winform 툴 개발(유니티에서 사용하기전 API TEST)            
            - c++ 쓰레드 구현.
            - opencv API 를 활용한 영상 스트리밍 시스템 구현.

            <mark>유니티 카메라뷰 프로그램</mark>
            - GUI(다중 모니터 활성화를 위한 UGUI Canvas 작업)
            - 소켓 통신 클라이언트 개발
            - custom opencv sdk 플러그인 연동
            - 영상 스트리밍 시스템
            - 다중 모니터 활성화 기능 구현

            <mark>유니티 로봇체험 프로그램</mark>
            - GUI(HUD)
            - 소켓 통신 클라이언트 개발
            - User Controller
            - custom opencv sdk 플러그인 연동
            - 영상 스트리밍 시스템
            - 360카메라 스트리밍 연동

            <mark>유니티 시스템제어 프로그램</mark>
            - GUI(미니맵 및 로봇상태, 로그 출력)
            - 소켓 통신 클라이언트 개발
            - google map static api 연동

      - layout: left
        title: 뮤엠교육
        link: mumenglish.com
        # link_text: boringcompany.com
        sub_title: Unity Developer
        caption: 2017.09 ~ 2019.07
        quote: >
          <mark>Unity</mark> <mark>C#</mark> <mark>AndroidJava</mark> <mark>Objective-C</mark> <mark>Gitlab</mark> <mark>BonoboGit</mark> <mark>AndroidStudio</mark> <mark>Xcode</mark>
        description: | # this will include new lines to allow paragraphs
            - [뮤고박스 MU:GO BOX](https://play.google.com/store/apps/details?id=com.mum.qbox&hl=ko) 유니티 안드로이드 앱 개발            
            - 뮤고박스 교사용 PC 프로그램 개발(Unity Standalone)
            - [뮤고스쿨](https://youtu.be/jfDnUqAfB7w) 안드로이드 네이티브 앱 및 유니티 안드로이드 앱 개발(유치원 내부 서비스)
            - 뮤고스쿨 교사용 PC 프로그램 유지보수(c# winform 및 Unity Standalone)
            - [nsis](https://nsis.sourceforge.io) 를 이용한 PC 교사용 프로그램 배포시스템 구축
            - Jenkins 를 이용한 apk 및 에셋번들 빌드 자동화
            - 에셋번들 시스템
            - 데이터 시스템
            - 3D 캐릭터 및 환경
            - 카메라 시스템
            - [WebRTC](https://because-why-not.com/webrtc/) 를 이용한 소환수업 개발
            - 네트워크 시스템(HTTP, Socket, WebSocket) 연동
      
      - layout: left
        title: Valofe
        link: valofe.com        
        sub_title: Unity Developer
        caption: 2017.03 ~ 2017.09
        quote: >
          <mark>Unity</mark> <mark>C#</mark> <mark>AndroidJava</mark> <mark>Objective-C</mark> <mark>Github</mark> <mark>SVN</mark> <mark>Redmine</mark> <mark>Xcode</mark> <mark>EZGUI</mark> <mark>Confluence</mark>
        description: | # this will include new lines to allow paragraphs
            - Google, AppStore, OneStore, WebPlayer 빌드 배포 및 서비스
            - 대만 로컬라이징 및 신규런칭(마이카드 연동)
            - Jenkins Slave Node 를 활용한 유니티iOS 빌드 자동화 구축
            - HTTP Manager 개발
            - 리뷰서버 전환 시스템(iOS 검수전용)
            - 결제 시스템(웹뷰 상점, 빌링매니저)
            - git branch 통합(Dev, Stage, Live)

      - layout: left
        title: YJM Games
        link: yjmgames.com        
        sub_title: Unity Developer
        caption: 2016.07 ~ 2017.01
        quote: >
          <mark>Unity</mark> <mark>C#</mark> <mark>AndroidJava</mark> <mark>Objective-C</mark> <mark>SVN</mark> <mark>Python</mark> <mark>VS2015</mark> <mark>Xcode</mark> <mark>NGUI</mark> <mark>Mantis</mark>
        description: | # this will include new lines to allow paragraphs
            - Android 이란 [바자르(로컬마켓)](https://developers.cafebazaar.ir/en/) 런칭
            - 이란 로컬라이징 및 SDK 연동
            - Data System
            - Jenkins 를 이용한 유니티 빌드 자동화 구축
            - UI System 리팩토링
            - 컨텐츠 개발
            - 캐릭터툴 개발

      - layout: left
        title: Picneko Creative
        link: www.softnyx.co.kr
        sub_title: Unity Developer
        caption: 2015.04 ~ 2016.03
        quote: >
          <mark>Unity</mark> <mark>C#</mark> <mark>AndroidJava</mark> <mark>Objective-C</mark> <mark>Github</mark> <mark>Python</mark> <mark>VisualStudio</mark> <mark>Xcode</mark> <mark>JIRA</mark> <mark>Slack</mark> <mark>Trello</mark> <mark>NGUI</mark> <mark>Prime31</mark> <mark>Sublime Text</mark>
        description: | # this will include new lines to allow paragraphs
            - Android, iOS 빌드배포 및 서비스(워스토리, 킹덤스토리)
            - Hudson 빌드시스템 유지보수 및 Jenkins 를 이용한 에셋번들 빌드 자동화
            - Python으로 dSYM 파일서버로 업로드 스크립트 개발
            - 컨텐츠 개발
            - SDK 연동([Kochava](https://www.kochava.com), [Amazon Appstore](https://developer.amazon.com/docs/cross-platform-plugins/cpp-use-appstore-sdk-unity.html), [Amazon In-App Purchasing](https://developer.amazon.com/docs/in-app-purchasing/iap-overview.html), [Adm](https://developer.amazon.com/docs/adm/overview.html), [Amazon Game Circle](https://developer.amazon.com/docs/gamecircle/faq-gamecircle.html), Facebook, GPGS)
            - 워스토리 호주, 북미 출시(Android, iOS, Amazon)
            - 텍스쳐 최적화
            - 툴 개발

      - layout: left
        title: BH Games        
        sub_title: Global localization
        caption: 2013.08 ~ 2014.08
        quote: >
          <mark>C++</mark> <mark>MFC</mark> <mark>DirectX</mark> <mark>ZerodinEngine</mark> <mark>STL</mark> <mark>SVN</mark> <mark>Redmine</mark> <mark>VS2008</mark> <mark>IOCP</mark>
        description: | # this will include new lines to allow paragraphs
            - 불패온라인 국내 라이브, 태국 서비스 런칭
            - 잭팟 시스템, 1:1 pvp 시스템, 아이템 교환시스템
            - 태국 로컬라이징
            - 패치 시스템
            - 툴 개발 및 유지보수
        
      - layout: left
        title: L&K Logic Korea
        link: logickorea.co.kr        
        sub_title: Client Programmer
        caption: 2012.03 ~ 2013.05
        quote: >
          <mark>C++</mark> <mark>MFC</mark> <mark>DirectX</mark> <mark>RideEngine</mark> <mark>STL</mark> <mark>SVN</mark> <mark>Gantt</mark> <mark>VS2008</mark> <mark>IOCP</mark>
        description: | # this will include new lines to allow paragraphs
            - 붉은보석2 온라인 신규개발
            - Tooltip, Skill UI, 시스템옵션
            - UI Engine 및 Tool 개선
            - Drop Item 개발
            - Actor, Player, NPC 관리 및 개선
            - 플레이어 이동 동기화

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 게임스쿨
        caption: 2010 - 2013
        sub_title: 게임프로그래밍 교육 1년과정 수료
        quote: >
          프로그래밍 기초 및 게임개발에 필요한 교육과정
        description: | # this will include new lines to allow paragraphs
          - C, C++, WinAPI, MFC, TCP/IP
          - DirectX 3D, 일리히트엔진, 유니티3, [cocos2d-x](https://github.com/cocos2d/cocos2d-x)
      
      - layout: left
        title: 극동대학교
        caption: 2010 - 2013
        sub_title: 게임소프트웨어 학과(졸업)
        quote: >
          프로그래밍 기초 및 졸업작품
        description: | # this will include new lines to allow paragraphs
          - 자료구조, 알고리즘
          - C, C++, C#
          - 네트워크
          - 그래픽스
          - 게임시나리오, 기획
          - 아이폰(objc) 2D 디펜스게임(졸업작품)


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
